---

## Social Card [1200x630]
social-card: "/assets/images/favicons/social-card.png"

## Social Card twitter [1200x600]
social-card-twitter: "/assets/images/favicons/social-card-twitter.png"

medium-posts-ids:
  - eddcd0a8e3f8
  - d589acbb9e72
  - adf7c1f63c83
  - 74b9877672d2
  - 92eec482c323
  - 619cd24c23dd
  - 2127d7b7cdc5
  - 3aaceb97b7a8
  - 269d10d0f853
