# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#

defaults: &defaults
  working_directory: ~/circleci/innovazione.gov.it
  add_ssh_keys: &add_ssh_keys
    fingerprints:
      - "6b:79:94:b3:2b:d1:e5:57:5c:44:15:ed:7a:9d:c1:8f"
  restore_cache: &restore_cache
    keys:
      - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - v1-dependencies-
  save_cache: &save_cache
    paths:
      - ./vendor/bundle
    key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  docker:
    - image: circleci/ruby:2.6.5
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        BUNDLER_VERSION: 2.0.1

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - add_ssh_keys: *add_ssh_keys
      - checkout

      # Retrieves Bundler version from Gemfile.lock
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      # Version check
      - run:
          name: Check versions
          command: |
            ruby --version
            bundle --version
            docker --version

      # Download and cache dependencies
      - restore_cache: *restore_cache

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache: *save_cache

      # Build the site
      - run:
          name: Build
          command: |
            bundle exec jekyll build

      # Test the site
      - run:
          name: Test with HTML Proofer
          command: |
            bundle exec htmlproofer ./_site --check-html --allow-hash-href --only-4xx --alt-ignore '/.*/'

      - persist_to_workspace:
          root: ~/circleci
          paths:
            - innovazione.gov.it

      - store_artifacts:
          path: ~/circleci/innovazione.gov.it/_site

  deploy-production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci
      - add_ssh_keys: *add_ssh_keys
      - checkout:
          path: /tmp/gh-pages
      - deploy:
          name: Update GitHub Pages
          command: |
            git config --global user.email no-reply@teamdigitale.governo.it
            git config --global user.name "Deploy Bot"

            cd /tmp/gh-pages
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .

            cp -a ~/circleci/innovazione.gov.it/_site/. .
            mkdir -p .circleci && cp -a ~/circleci/innovazione.gov.it/.circleci/. .circleci/.
            # echo "innovazione.gov.it" > CNAME

            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin gh-pages

workflows:
  version: 2

  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only:
                - master
